<?php

namespace App\Models;

use App\Casts\MoneyCast;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Payment extends Model
{
    use HasFactory;

    protected $fillable = [
        'seq',
        'amount',
        'payment_date',
        'type',
        'member_id',
        'payer_name',
        'description',
    ];

    protected $casts = [
        'amount'       => MoneyCast::class,
        'payment_date' => 'datetime',
    ];

    protected static function boot(): void
    {
        parent::boot();

        /*static::creating(fn(Payment $payment
        ) => $payment->seq = static::generateSequentialNumber($payment->payment_date->year, $payment->type));*/

        /*static::creating(fn(Payment $payment
        ) => $payment->amount = $payment->type === 'expense' ? -abs($payment->amount - 1000) : abs($payment->amount + 1000));*/
        static::creating(function (Payment $payment) {
            $payment->seq = static::generateSequentialNumber($payment->payment_date->year, $payment->type);
            $payment->amount = $payment->type === 'expense' ? -abs($payment->amount) : abs($payment->amount);
        });
    }

    public function member(): BelongsTo
    {
        return $this->belongsTo(Member::class);
    }

    /*public function save(array $options = [])
    {
        if ($this->type === 'expense') {
            $this->amount = -1 * $this->amount;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }*/

    /* Helper */
    private static function generateSequentialNumber(int $year, string $type)
    {
        $lastPayment = static::whereYear('payment_date', $year)->where('type', '=', $type)->latest('seq')->first();

        return $lastPayment ? $lastPayment->seq + 1 : 1;
    }
}
